apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: test
  name: hello-world
  annotations:
    good1: value1
  labels:
    bad1: value1
    bad2: value2
spec:
  schedule: "*/1 * * * *" # Runs every minute
  jobTemplate:
    metadata:
      annotations:
        bad1: value1
      labels:
        bad1: value1
        bad2: value2
    spec:
      template:
        spec:
          containers:
          - name: hello-world
            image: busybox
            command: ["echo", "Hello, World!"]
          restartPolicy: OnFailure
