apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-dep
    prohibit2: value2
  name: my-dep
  namespace: test
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-dep
        key2i: bb
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
