apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-dep
    prohibit1: value1
    prohibit2: value2
  name: my-dep
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-dep
        prohibit4: any
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: bad1
          value: value1
        - name: bad2
          value: value2
        - name: bad3
          value: anything
        resources: {}
status: {}
