apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "demo1"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments","replicasets","daemonsets","statefulsets"]
    - apiGroups:   ["batch"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["jobs","cronjobs"]
  variables:
  - name: blacklist
    expression: '{"prohibit1": "value1*", "prohibit2": "value2*", "prohibit4": ""}'
  validations:
    - expression: '!has(object.metadata.labels) || !variables.blacklist.all(key, key in object.metadata.labels && object.metadata.labels[key].matches(variables.blacklist[key]))'
      message: '❌ operator: contains_all, labels cannot use ALL blacklist key/value'
