apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "demo1"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments","replicasets","daemonsets","statefulsets"]
    - apiGroups:   ["batch"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["jobs","cronjobs"]
  variables:
  - name: allowlist
    expression: '{"app": "", "good1": "value1*", "good2": "value2*", "good3": ""}'
  - name: dataset1
    expression: 'has(object.metadata.labels) ? object.metadata.labels : []'
  - name: dataset2
    expression: 'has(object.spec.template.metadata.labels) ? object.spec.template.metadata.labels : []'
  validations:
    - expression: '
    (
       !has(object.metadata.labels) || 
       !variables.dataset1.exists(x, !(x in variables.allowlist &&  matches(variables.dataset1[x], variables.allowlist[x])))
    )
     &&
     (
       !has(object.spec.template.metadata.labels) || 
       !variables.dataset2.exists(x, !(x in variables.allowlist && matches(variables.dataset2[x], variables.allowlist[x])))
     )
    '
      message: '❌ operator: contains_other_than, labels can only use predefined key/value'
