apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  annotations:
    good1: value1
    must1: value1
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
