apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    bad1: value1
    bad2: value2
    bad3: any
  labels:
    app: my-dep
    prohibit1: value1
    prohibit2: value2
  name: my-dep
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-dep
        prohibit4: any
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: bad1
          value: value1
        resources: {}
status: {}
