apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    good1: value1
    bad1: value12222222222
  labels:
    app: my-dep
    bad: value2
  name: my-dep
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      annotations:
        good2: value1
      labels:
        app: my-dep
        prohibit4: any
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: bad2
          value: value2
        resources: {}
status: {}
