apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  annotations:
    good1: value1
    bad1: value12222222222
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: bad2
      value: value2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
