apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: good2
      value: value2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
