apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-dep
  annotations:
    test2: bbb_only_in_deploy_level
  name: my-dep
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-dep
      annotations:
        test1: aaa_only_in_pod_level
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: bad1
          value: value1
        resources: {}
status: {}
